spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: restaurant-order
  rabbitmq:
    host: localhost
    port: 5672
    username: amit
    password: amit

server:
  port: 8003

management:
  endpoints:
    web:
      exposure:
        include: "*"
      expose: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
